c8/client.py
c8/constants.py

Updated the documentation and default tenant to guest in tenant and fabric connection.
- This change requires a documentation update

1. use guest tenant as default tenant

---

README.md
c8/fabric.py
c8/stream_collection.py
docs/document.rst
docs/fabric.rst
docs/overview.rst
docs/stream.rst

Made changes to support new REST API for getting detailed list of fabrics. Added function called as fabric_details. Also added support to get consumer_type as argument while creating new stream subscriber. Made the respective documentation changes as well.
Tested on Multi-Region QA1 federation.
Review:
@kartikeya-macrometa 
@durgagokina

Fabric detail

---

README.md
c8/fabric.py
c8/http.py
c8/stream_collection.py
docs/fabric.rst
docs/overview.rst
docs/stream.rst

1. Added dclist-detail function which returns details of all datacenters.
2. Removed nonpersistent streams from stream_colllection apis and made requisite changes to code to support the change.
3. Updated the documentation accordingly.
Tested on 2-region federation.

Dclist all

---

c8/client.py
c8/connection.py
c8/exceptions.py
c8/function.py

Added support for Function APIs

---

README.md
c8/function.py
docs/function.rst

Added documentation for function APIs

---

README.md
c8/exceptions.py
c8/tenant.py

- Updated README.md with saved queries examples
- Added saved queries related exceptions
- Added definitions for APIs
* C8 Version:

Added support for saved queries APIs for user

---

README.md
docs/tenant.rst

Fixed save user queries doc

---

c8/exceptions.py
c8/function.py
c8/http.py

Added function execution API

---

c8/collection.py
c8/job.py
setup.py

Reverted the changes made as part of API cleanup in pyC8.

Revert the changes made to pyc8 as part of API cleanup

---

c8/collection.py
c8/function.py
c8/job.py
setup.py

Fixed indentation errors in c8/collection.py

---

c8/exceptions.py
c8/tenant.py

Changes for adding validation in query name for saved queries.

saved queries: add validation for white spaces

---

c8/fabric.py

https://github.com/Macrometacorp/C8Platform/issues/673
* C8 Version:

Local collection

---

c8/exceptions.py
c8/fabric.py

https://github.com/Macrometacorp/C8Platform/issues/717
* C8 Version:

Added event apis

---

c8/client.py

Added api- prefix to urls

---

c8/fabric.py
c8/stream_apps.py
docs/streamapps.rst

Bug fix -- parse multiline stream app definition string to single line definition and pass it into the request
Added stream app doc file and steps to use stream app functions
Tested  locally using local pyC8

bug fix multiline to singleline

---

c8/fabric.py
c8/stream_apps.py
docs/streamapps.rst

updated stream app drivers

---

c8/fabric.py
c8/stream_collection.py
requirements.txt
setup.py

Removed pulsar-client dependency and used websockets to connect to the streams. Changes will be published in pyC8 version 0.15.2. Automation tests updated accordingly.
Fixes  issue C8Drivers - Eliminate `pulsar-client` in pyC8. #856
It has been tested locally, and on CircleCI.
Tested locally using local pyC8 changes.
Tested on CircleCI using C8Automation and pyC8 release version 0.14.7
* pyC8 Version used for testing: 0.14.7
* Final version after testing: 0.15.2

Change websocket

---

docs/stream.rst

Added proper examples to show
1) How to use stream.
2) How to send data to a stream 
3) How to receive data from a stream
[test-stream-pyC8.py.zip](https://github.com/Macrometacorp/pyC8/files/4389076/test-stream-pyC8.py.zip)

Changes in docs

---

c8/client.py

Reduce steps

---

c8/collection.py

Stream auth

---

README.md
c8/client.py
c8/fabric.py
docs/collection.rst
docs/overview.rst

Added filter based on collection model to `get_collections` function which enables users to get collections by Collection Model. If collectionModel is not specified then it will return all collections.
Fixes #1327 of pyc8 driver
It has been tested locally using following script.
```
import sys
import pprint
sys.path.append('/macrometa/pyc8/c8')
from c8 import C8Client
client = C8Client(protocol='https', host='gdn1.macrometa.io', port=443,
email='guest@macrometa.io', password='guest',
geofabric='_system')
collections = client.get_collections(collectionModel="KV")
print(collections)
```

Dev issue 1327

---

c8/exceptions.py
c8/fabric.py

Added a bug fix. `get_collection` was failing silently with no error.
Fixes issue #1622
Tested locally using pyc8 import using `sys` package.

bug fix #1622

---

c8/client.py
c8/exceptions.py
c8/fabric.py
c8/search.py
docs/search.rst

Added search and analyser apis to pyc8. Added docs for the same.
* C8 Version:

Search view ticket #1336

---

README.md
c8/stream_collection.py

Fixes Macrometacorp/C8Platform#1490

Base64-encode messages to a producer

---

c8/client.py
c8/fabric.py
c8/tenant.py

Add `stream` flag to `create_collection()`

Stream collection

---

c8/client.py
c8/collection.py
c8/fabric.py
c8/stream_collection.py
c8/tenant.py
docs/c8ql.rst
docs/conf.py
docs/index.rst
docs/indexes.rst
docs/search.rst

Fix documentation formatting issues across several modules. When merged to master on the main public repo, it should trigger a rebuild for readthedocs.
Fixes # PYDR-65

[PYDR-65] Fix doc formatting issues

---

c8/api.py
c8/client.py
c8/connection.py
c8/exceptions.py
c8/executor.py
c8/tenant.py

Fix for https://macrometa.atlassian.net/browse/PYDR-93
updating user apis to remove the _fabric/{fabric} part since user management is at tenant level and not fabric level
https://macrometa.atlassian.net/browse/PYDR-93
Task
Made the changes in the local copy of repo did a local setup of pyC8 repo and tested the changes using scripts like the following and testing the various user management functions:
from c8 import C8Client
print("--- Connecting to C8")
client = C8Client(protocol='https', host='<your host URL>', port=443, email='<your email>', password='<your password>', geofabric='_system')
print("CONNECTED")
resp = client.get_users()
print(resp)
resp = client.get_user("root")
print(resp)
resp = client.get_permissions("root") …

Updating USER api URLs

---

c8/client.py

FIxes update_document_many and delete_document_many methods in client.py
https://macrometa.atlassian.net/browse/PYDR-81
https://macrometa.atlassian.net/browse/PYDR-75
Use example script like the following by updating your credentials and creating a collection named say test:
from c8 import C8Client
print("--- Connecting to C8")
client = C8Client(protocol='https', host='gdn.paas.macrometa.io', port=443, email='nemo@nautilus.com', password='xxxxxx', geofabric='_system')
print("CONNECTED")
data = [
{"_key":"ljuba","country":"Serbia"},{"_key":"7tt77t","name":"Edgar"}
]
resp = client.import_bulk(collection_name="test", documents=data, details=True, replace=True)
print(resp)
resp = client.export(collection_name="test", offset=0, …

Small fixes for update and delete many docs at once

---

c8/client.py
c8/exceptions.py
c8/tenant.py

1. Updating tenant API with displayName, contact info, plan, attribution and metadata as per the current requirements of the tenant API.
2. Updating user API with displayName during creation and newEmail object during update.
3. Removing replace user api it never used to work and we have removed the api from our api references as well.(Ticket: https://macrometa.atlassian.net/browse/DB-1428)
https://macrometa.atlassian.net/browse/DB-1259
https://macrometa.atlassian.net/browse/PYDR-95
https://macrometa.atlassian.net/browse/DB-1428
For Tenant API (create, update) use script and fill your credentials:
from c8 import C8Client
print("--- Connecting to C8")
client = C8Client(protocol='https', host='', email='', port=443, password='', …

Updating Tenant and User APIs

---

c8/client.py
c8/connection.py
c8/fabric.py
c8/tenant.py
tests/conftest.py
tests/helpers.py

Updating conftest to progress with completing/correcting tests with the current APIs. I have removed some code which is not needed and added some to make it work.
We can start running tests individually after this and start correcting/adding and covering all the existing api methods
commands to be used:
cd pyC8/tests
pytest -v filename
* C8 Version:

Updating conftest to progress with testing

---

tests/conftest.py
tests/test_user.py

git keyword got added due to some auto-complete feature in my code editor, need to remove that
Also updated tests for user apis in test_user.py with the appropriate methods and removed third Test Function as it is not valid anymore since we can't create users while creating a fabric. Users are not at fabric level but tenant level.

Removing a typo/auto complete

---

c8/api.py
c8/apikeys.py
c8/connection.py
c8/executor.py
c8/fabric.py
c8/tenant.py
tests/conftest.py
tests/test_c8ql.py
tests/test_cursor.py

Updated test_c8ql.py (also added sql test case), test_cursor.py and change customPrefix to custom_prefix
* C8 Version:

Updated test_c8ql.py, test_cursor.py and changed customPrefix to custom_prefix

---

c8/exceptions.py
c8/fabric.py
tests/conftest.py
tests/e2e/test_collection.py
tests/test_collection.py

Added 2 new functions in fabric.py that will be used for test purposes, and also are going to match with 2 endpoints that are available through API Reference, the functions are collection_figures and update_collection_properties, also test_collection.py has been updated and added a new e2e test for collections
* C8 Version:

Feature test collection update

---

c8/collection.py
tests/test_index.py

Added test_add_ttl_index(), changed index_id by index_name in delete_index(), and modified some properties for assetion

test_index updated, rename _add_index in collection.py and remove raw request from add_hash_index

---

tests/test_fabric.py

update fabric test, deleted engine() and details() method assert, rename db

Update and rename test_database.py to test_fabric.py

---

c8/stream_collection.py

Removed some unnecessary print statements which were probably used for debugging it seems but is confusing for the user
* C8 Version:

Removed some unnecessary print statements

---

c8/client.py
tests/e2e/test_redis.py

- Added sorted set commands
- Added tests for sorted set commands
End-to-end tests are included in the codebase

Pydr 125 add sorted set commands to redis interface

---

c8/exceptions.py
c8/fabric.py
tests/test_fabric.py

Added fabric metadata APIs
Added missing datacenter APIs

PYDR-129 & PYDR-130 Add missing Fabric APIs and Datacenter APIs

---

c8/client.py
c8/connection.py
c8/executor.py
c8/plan/plan_interface.py
tests/e2e/test_plans.py

Added property annotation for plan in client.py to follow code structure and added custom_prefix for functions API calls

adding property annotation for plan in client.py

---

tests/url_tester.py

Added a script to test website doc URLs which will be used in our sdk docs.
website doc paths tend to change frequently as we continue to restructure our official docs.
This could lead us to have broken links in our sdk docs (pyC8 docs)
So this script will help us to detect broken links and  identify them
* C8 Version:

Added a script to test website doc URLs which will be used in our sdk docs

---

GETTING_STARTED.md

Updating GETTING_STARTED .md with following sections:
1. Returning data in batches
2. Query Workers
3. truncate/delete collection
4. Realtime updates of collection (collection as a stream)
5. Streams
6. Stream Workers

PYDR-132 Update GETTING_STARTED.md

---

c8/client.py
c8/connection.py
c8/tenant.py
tests/e2e/conftest.py
tests/e2e/test_plans.py
tests/test_client.py
tests/test_user.py

added get_jwt in client.py with changes from the https://github.com/Macrometacorp/pyC8/pull/119
* C8 Version:

added get_jwt in client.py

---

GETTING_STARTED.md
examples/document_store_crud.py
examples/get_data_in_batches.py
examples/get_realtime_updates_from_collection.py
examples/query_workers.py
examples/stream_workers.py
examples/streams.py
examples/working_with_c8ql.py
tests/e2e/test_sql.py

CRUD in Getting started
Update GETTING_STARTED.md
1. Auth - Connect to GDN
2. Create a collection
3. CRUD Operations for collections
4. Working with C8QL
* C8 Version:

PYDR-131-update-getting-started-md-in-py-c-8

---

examples/document_store_crud.py
examples/get_data_in_batches.py
examples/get_realtime_updates_from_collection.py
examples/query_workers.py
examples/redis/how-to-use-redis.py
examples/stream_workers.py
examples/streams.py
examples/working_with_c8ql.py

Added redis code examples in the examples folder.

Added redis code examples

---

README.md
c8/client.py
c8/fabric.py
tests/conftest.py
tests/e2e/conftest.py
tests/test_apikeys.py
tests/test_client.py
tests/test_collection.py
tests/test_cursor.py
tests/test_graph.py
tests/test_permission.py
tests/test_query_workers.py
tests/test_stream.py
tests/test_streamapps.py
tests/url_tester.py

FIxed tests to adapt with new 17.12 as well. We will still see 4 test cases fail as there are two bugs which are not fixed from c8 connectors side.. so once they are fixed we should have 100 percent success on tests.
Removed Email and Password authentication from testsso that our github actions keep only apikeys as secrets.
Also fixed the path variables in tests/url_tester.py and tests/test_collections.py so that it can be run from anywhere not just tests folder.
https://macrometa.atlassian.net/browse/PYDR-134
By pyc8 tests

PYDR-134 Fixing tests to adapt with new 17.12 as well also removed password, email authentication in tests

---

GETTING_STARTED.md

Added Note style in some examples for GETTING_STARTED.md

Feature adding note style

---

GETTING_STARTED.md

Updated GETTING_STARTED.md

---

GETTING_STARTED.md

Recently the structure of the docs was changed for certain sections which caused broken links in our GETTING_STARTED.md

Fixing broken links in GETTING_STARTED.md

---

.github/workflows/tag-and-publish.yml
c8/__init__.py
c8/client.py
c8/stream_collection.py

Added missing compression types for streams.
Changed GithubAction
Running integration tests

Pydr 159 add missing compression types for streams
